import type { NextPage } from "next";
import React from "react";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Link from "next/link";

import { useRouter } from "next/router";
import Header from "../component/Header";
import Footer from "../component/Footer";
import Headerhover from "../component/HeaderHover";
import Services from "./Services";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main_layout_container}>
        <Headerhover/>

        <div className={styles.banner_container}>
          <div className={styles.banner_img}>
            <Image
              src="/images/banner.jpg"
              alt="banner"
              layout="fill"
              objectFit={"cover"}
            />
          </div>

          <div className={styles.banner_contain_container}>
            <div className={styles.contain_text_area_container}>
              <h1>
                Making good health accessible <span>to all.</span>
              </h1>
              <p>Book same day appointments. No subscriptions.</p>
            </div>

            <div className={styles.contain_box_container}>
              <div className={styles.box_heading}>
                <p>Book an Appointment</p>
              </div>

              <div className={styles.box_item_container}>
                <div className={styles.box_primary_care_container}>
                  <div className={styles.box_circle}> </div>
                  <div className={styles.box_contain}>
                    <h3>Primary Care</h3>
                    <p>Ideal for preventive Care </p>
                  </div>
                  <div className={styles.box_date}>
                    <p>Next: Today 10pm</p>
                  </div>
                </div>

                <div className={styles.box_urgent_care_container}>
                  <div className={styles.box_circle}> </div>
                  <div className={styles.box_contain}>
                    <h3>Urgent Care</h3>
                    <p>Ideal for immediate medical attention</p>
                  </div>
                  <div className={styles.box_date}>
                    <p>Next: Today 6pm</p>
                  </div>
                </div>

                <div className={styles.box_virtual_care_container}>
                  <div className={styles.box_circle}> </div>
                  <div className={styles.box_contain}>
                    <h3>Virtual Care</h3>
                    <p>Video with your health team</p>
                  </div>
                  <div className={styles.box_date}>
                    <p>Next: Today 7pm</p>
                  </div>
                </div>
              </div>

              <div className={styles.box_btn}>
                <button>Book In Appointment</button>
              </div>
            </div>
          </div>
        </div>

        <main className={styles.main}>
          <div className={styles.main_top_contain}>
            <h1>
              A friendlier healthcare experience,
              <span> without the membership fees.</span>
            </h1>
            <button>Book In Appointment</button>
          </div>

          <div className={styles.information_item_container}>
            <div className={styles.appointments_item_container}>
              <div className={styles.item_img}>
                <Image
                  src="/images/appointments.svg"
                  alt="item"
                  layout="fill"
                  // objectFit={"cover"}
                />
              </div>

              <h1>Book same day appointments</h1>
              <p>Primary, urgent, and virtual care visits on YOUR schedule.</p>
            </div>

            <div className={styles.team_item_container}>
              <div className={styles.item_img}>
                <Image
                  src="/images/team.svg"
                  alt="item"
                  layout="fill"
                  // objectFit={"cover"}
                />
              </div>
              <h1>Chat with your health team</h1>
              <p>
                Get treated for a range of symptoms & conditions right from your
                smartphone.
              </p>
            </div>

            <div className={styles.doorstep_item_container}>
              <div className={styles.item_img}>
                <Image
                  src="/images/doorstep.svg"
                  alt="item"
                  layout="fill"
                  // objectFit={"cover"}
                />
              </div>
              <h1>Prescriptions at your doorstep</h1>
              <p>
                Get your medications sent straight to your chosen pharmacy or to
                your door—whatever works for you.
              </p>
            </div>

            <div className={styles.place_item_container}>
              <div className={styles.item_img}>
                <Image
                  src="/images/place.svg"
                  alt="item"
                  layout="fill"
                  // objectFit={"cover"}
                />
              </div>
              <h1>All your health in one place</h1>
              <p>
                Access your medical charts, complete records, and test results
                immediately.
              </p>
            </div>
          </div>
      

     
          <div className={styles.move_in_container}>
            <div className={styles.move_in_top_contain}>
              <h1>We're movin' in!</h1>
              <p>
                Modern clinics, designed from the ground up, with patient
                experience in mind. Check out our new locations.
              </p>
            </div>

            <div className={styles.move_in_img_contain_container}>
              <div className={styles.move_in_img}>
                <Image
                  src="/images/home-img.jpg"
                  alt="location"
                  objectFit="cover"
                  layout="fill"
                />
              </div>

              <div className={styles.move_in_location_container}>
                <div className={styles.santa_clara_square_location}>
                  <h2>Santa Clara Square</h2>
                  <p>2712 Augustine Dr. Santa Clara, CA 95054</p>
                  <button>View Location</button>
                </div>

                <div className={styles.san_pedro_square_location}>
                  <h2>San Pedro Square</h2>
                  <p>28 N. Almaden Avenue, San Jose, CA 95110</p>
                  <button>View Location</button>
                </div>

                <div className={styles.almaden_ranch_location}>
                  <h2>Almaden Ranch</h2>
                  <p>5120 Cherry Ave, San Jose, CA 95118</p>
                  <button>View Location</button>
                </div>

                <div className={styles.hillsdale_mall_location}>
                  <h2>Hillsdale Mall</h2>
                  <p>70 31st Ave, San Mateo, CA 94403</p>
                  <button>View Location</button>
                </div>

                <div className={styles.redwood_plaza_location}>
                  <h2>Redwood Plaza</h2>
                  <p>784 Admiral Callaghan Ln, Vallejo, CA 94591</p>
                  <button>View Location</button>
                </div>

                <div className={styles.grand_plaza_location}>
                  <h2>Grand Plaza</h2>
                  <p>109 S. Las Posas Rd, San Marcos, CA 92078</p>
                  <button>View Location</button>
                </div>
              </div>
            </div>
          </div>

          <div className={styles.phone_app_container}>
            <div className={styles.phone_app_img}>
              <Image
                src="/images/mobile-img.jpg"
                alt="app-data"
                objectFit="cover"
                layout="fill"
              />
            </div>

            <div className={styles.phone_app_contain_container}>
              <div className={styles.phone_app_top_contain}>
                <h1>Get treated right from your phone.</h1>
                <div className={styles.mobile_no_contain}>
                  <input type="number" placeholder="Phone Number" />
                  <button>Text Me The App</button>
                </div>
                <p>AVAILABLE IN THE APP STORE AND GOOGLE PLAY</p>
              </div>

              <div className={styles.phone_app_bottom_contain}>
                <div className={styles.mobile_phone_used_img}>
                  <Image
                    src="/images/mobile-phone-used-img.jpeg"
                    alt="app-data"
                    // objectFit="cover"
                    layout="fill"
                  />
                </div>

                <div className={styles.mobile_point}>
                  <p>
                    <span>»</span> Book same-day appointments
                  </p>
                  <p>
                    <span>»</span>Talk to a provider in real time
                  </p>
                  <p>
                    <span>»</span>Get care from the comfort of home
                  </p>
                  <p>
                    <span>»</span>Most insurance accepted
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className={styles.covid_container}>
            <div className={styles.covid_img}>
              <Image
                src="/images/covid-img.jpg"
                alt="app-data"
                objectFit={"cover"}
                layout="fill"
              />
            </div>

            <div className={styles.covid_contain_container}>
              <div className={styles.covid_top_contain}>
                <p>
                  CAPTAIN NAJERA, LA FIRE DEPT, DODGER STADIUM VACCINATION SITE:
                </p>
                <h1>
                  In order to make this work well, we have a collaborative
                  effort with Carbon Health... Without them this wouldn’t work.
                </h1>
                <button>See All COVID-19 Initiatives</button>
              </div>
              <div className={styles.covid_bottom_contain}>
                <div className={styles.covid_bottom_left}>
                  <p>TESTS CONDUCTED</p>
                  <h1>1.44 million +</h1>
                </div>
                <div className={styles.covid_bottom_center}>
                  <p>VACCINES ADMINISTERED</p>
                  <h1>1.55 million +</h1>
                </div>

                <div className={styles.covid_bottom_right}>
                  <p>UCSF DIGITAL HEALTH AWARDS</p>
                  <h1>COVID Patriot Best Delivery & Decision Support Award</h1>
                </div>
              </div>
            </div>
          </div>
        </main>

        <Footer /> 
      </div>
    </div>
  );
};

export default Home;
